"""Build and execute portable Smalltalk runtime regressions on the host."""

import argparse
import asyncio
import os
from pathlib import Path
import subprocess

import http_test


async def network_test(executable, root, clients):
    process = await asyncio.create_subprocess_exec(str(executable), "--network", str(clients), cwd=root, stdout=asyncio.subprocess.PIPE)
    connections = []

    try:
        line = await asyncio.wait_for(process.stdout.readline(), 10)
        if not line.startswith(b"PORT "):
            raise RuntimeError("Server did not report its listening port: " + repr(line))

        port = int(line.split()[1])
        async def connect():
            connection = await asyncio.open_connection("127.0.0.1", port)
            connections.append(connection)
            return connection

        await asyncio.wait_for(asyncio.gather(*[connect() for _ in range(clients)]), 30)
        payloads = [bytes((index + offset) % 256 for offset in range(257)) for index in range(clients)]

        for (_, writer), payload in zip(connections, payloads):
            writer.write(payload[:1])

        await asyncio.sleep(0.02)

        for (_, writer), payload in zip(connections, payloads):
            writer.write(payload[1:129])

        await asyncio.sleep(0.02)

        for (_, writer), payload in zip(connections, payloads):
            writer.write(payload[129:])

        async def verify(reader, payload):
            actual = await reader.readexactly(len(payload))
            if actual != payload:
                raise AssertionError("Concurrent connection received another client's bytes")
            if await reader.read(1) != b"":
                raise AssertionError("Connection remained open after receive timeout")

        await asyncio.wait_for(asyncio.gather(*[
            verify(reader, payload) for (reader, _), payload in zip(connections, payloads)
        ]), 45)
        output, _ = await asyncio.wait_for(process.communicate(), 15)
        print(output.decode(), end="")

        if process.returncode != 0:
            raise RuntimeError("Socket regression failed: " + str(process.returncode))
    finally:
        for _, writer in connections:
            writer.close()

        await asyncio.gather(*[writer.wait_closed() for _, writer in connections], return_exceptions=True)

        if process.returncode is None:
            process.kill()
            await process.wait()


def link_application(root, sample, output, flags, objects, libraries, profile, launch_symbol, name):
    assembly = sorted(profile.resolve().glob("*.s"))

    if not assembly:
        raise ValueError("Application profile contains no assembly artifacts: " + str(profile))

    executable = output / (name + (".exe" if os.name == "nt" else ""))
    application_sources = [sample / "src/product/application_startup.c", sample / "examples/support/native_main.c"]
    arguments = flags[1:] + ["-DST_APPLICATION_LAUNCH_SYMBOL=" + launch_symbol]
    arguments += [str(source) for source in application_sources] + objects + [str(source) for source in assembly]
    arguments += libraries + ["-o", str(executable)]
    response = output / (name + "-link.rsp")
    response.write_text("\n".join('"' + argument.replace("\\", "/").replace('"', '\\"') + '"' for argument in arguments), encoding="utf-8")
    subprocess.run([flags[0], "@" + str(response)], check=True, cwd=root)
    return executable


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cc", default="clang")
    parser.add_argument("--build-dir", default="build/smalltalk-runtime")
    parser.add_argument("--clients", type=int, default=1024, help="Concurrent clients generated by the regression driver")
    parser.add_argument("--http-profile", type=Path, help="Generated assembly directory for the HTTP regression application on this host")
    parser.add_argument("--application-profile", type=Path, help="Generated assembly directory for an application to run to completion")
    parser.add_argument("--expected-exit", type=int, default=0)
    parser.add_argument("--launch-symbol", default="st_app_http_launch_descriptor")
    args = parser.parse_args()

    if args.clients < 1:
        parser.error("--clients must be positive")

    root = Path(__file__).resolve().parents[3]
    sample = root / "samples/smalltalk"
    output = (root / args.build_dir).resolve()
    output.mkdir(parents=True, exist_ok=True)
    platform = "windows" if os.name == "nt" else "posix"
    flags = [args.cc, "-std=c11", "-O2", "-g", "-Wall", "-Wextra", "-Wpedantic", "-Werror",
             "-I" + str(root / "include"), "-I" + str(sample / "include")]
    sources = sorted((sample / "src/runtime").rglob("*.c"))
    sources += sorted((sample / "src/platform" / platform).glob("*.c"))
    sources += [sample / "src/compiler/primitive.c"]
    objects = []

    for source in sources:
        name = "_".join(source.relative_to(sample).parts)
        obj = output / (name + ".o")
        subprocess.run(flags + ["-c", str(source), "-o", str(obj)], check=True, cwd=root)
        objects.append(str(obj))

    for name in ("fiber",):
        executable = output / (name + (".exe" if os.name == "nt" else ""))
        libraries = ["-lws2_32"] if os.name == "nt" else ["-lm", "-pthread"]
        subprocess.run(flags + [str(sample / "tests" / (name + "_test.c"))] + objects
                       + libraries + ["-o", str(executable)], check=True, cwd=root)
        subprocess.run([str(executable)], check=True, cwd=root, timeout=60)
        asyncio.run(network_test(executable, root, args.clients))

    if args.http_profile is not None:
        executable = link_application(root, sample, output, flags, objects, libraries, args.http_profile, args.launch_symbol, "http")
        asyncio.run(http_test.run(executable, args.clients, 2))

    if args.application_profile is not None:
        executable = link_application(root, sample, output, flags, objects, libraries, args.application_profile, args.launch_symbol, "application")
        result = subprocess.run([str(executable)], cwd=root, timeout=60)

        if result.returncode != args.expected_exit:
            raise AssertionError("Application exit status: " + str(result.returncode) + "; expected " + str(args.expected_exit))


if __name__ == "__main__":
    main()
