/*
 * Test program for ANVIL-generated floating-point math library
 * 
 * This C program links with the assembly code generated by generate_math.c
 * to test the floating-point math functions.
 * 
 * Build instructions:
 * 
 *   # 1. Generate the assembly code (choose your architecture):
 *   ./generate_math x86_64 > math_lib.s       # For x86-64 Linux
 *   ./generate_math arm64 > math_lib.s        # For ARM64 Linux
 *   ./generate_math arm64_macos > math_lib.s  # For ARM64 macOS
 *   ./generate_math ppc64le > math_lib.s      # For PowerPC64 LE
 * 
 *   # 2. Assemble the generated code:
 *   as math_lib.s -o math_lib.o               # Linux
 *   as -arch arm64 math_lib.s -o math_lib.o   # macOS ARM64
 * 
 *   # 3. Compile this test program:
 *   gcc -c test_math.c -o test_math.o
 * 
 *   # 4. Link everything together:
 *   gcc test_math.o math_lib.o -o test_math -lm
 * 
 *   # 5. Run the test:
 *   ./test_math
 */

#include <stdio.h>
#include <math.h>
#include <stdbool.h>

/* Declare the external functions from our generated assembly */
extern double fp_add(double a, double b);
extern double fp_sub(double a, double b);
extern double fp_mul(double a, double b);
extern double fp_div(double a, double b);
extern double fp_neg(double a);
extern double fp_abs(double a);

/* Tolerance for floating-point comparison */
#define EPSILON 1e-10

/* Compare two doubles with tolerance */
static bool fp_equal(double a, double b)
{
    return fabs(a - b) < EPSILON;
}

/* Test result tracking */
static int tests_passed = 0;
static int tests_failed = 0;

/* Test macro */
#define TEST(name, got, expected) \
    do { \
        if (fp_equal(got, expected)) { \
            printf("  [PASS] %s: got %.6f, expected %.6f\n", name, got, expected); \
            tests_passed++; \
        } else { \
            printf("  [FAIL] %s: got %.6f, expected %.6f\n", name, got, expected); \
            tests_failed++; \
        } \
    } while (0)

int main(void)
{
    printf("=== ANVIL Floating-Point Math Library Test ===\n\n");
    
    /* Test values */
    double a = 10.5;
    double b = 3.5;
    double neg_val = -7.25;
    
    printf("Test values: a = %.2f, b = %.2f, neg_val = %.2f\n\n", a, b, neg_val);
    
    /* Test fp_add */
    printf("Testing fp_add:\n");
    TEST("fp_add(10.5, 3.5)", fp_add(a, b), a + b);
    TEST("fp_add(0.0, 0.0)", fp_add(0.0, 0.0), 0.0);
    TEST("fp_add(-5.0, 5.0)", fp_add(-5.0, 5.0), 0.0);
    TEST("fp_add(1.1, 2.2)", fp_add(1.1, 2.2), 3.3);
    printf("\n");
    
    /* Test fp_sub */
    printf("Testing fp_sub:\n");
    TEST("fp_sub(10.5, 3.5)", fp_sub(a, b), a - b);
    TEST("fp_sub(5.0, 5.0)", fp_sub(5.0, 5.0), 0.0);
    TEST("fp_sub(0.0, 3.14)", fp_sub(0.0, 3.14), -3.14);
    TEST("fp_sub(100.0, 25.5)", fp_sub(100.0, 25.5), 74.5);
    printf("\n");
    
    /* Test fp_mul */
    printf("Testing fp_mul:\n");
    TEST("fp_mul(10.5, 3.5)", fp_mul(a, b), a * b);
    TEST("fp_mul(2.0, 3.0)", fp_mul(2.0, 3.0), 6.0);
    TEST("fp_mul(-2.0, 3.0)", fp_mul(-2.0, 3.0), -6.0);
    TEST("fp_mul(0.5, 0.5)", fp_mul(0.5, 0.5), 0.25);
    printf("\n");
    
    /* Test fp_div */
    printf("Testing fp_div:\n");
    TEST("fp_div(10.5, 3.5)", fp_div(a, b), a / b);
    TEST("fp_div(10.0, 2.0)", fp_div(10.0, 2.0), 5.0);
    TEST("fp_div(1.0, 4.0)", fp_div(1.0, 4.0), 0.25);
    TEST("fp_div(-9.0, 3.0)", fp_div(-9.0, 3.0), -3.0);
    printf("\n");
    
    /* Test fp_neg */
    printf("Testing fp_neg:\n");
    TEST("fp_neg(10.5)", fp_neg(a), -a);
    TEST("fp_neg(-7.25)", fp_neg(neg_val), -neg_val);
    TEST("fp_neg(0.0)", fp_neg(0.0), -0.0);
    TEST("fp_neg(1.0)", fp_neg(1.0), -1.0);
    printf("\n");
    
    /* Test fp_abs */
    printf("Testing fp_abs:\n");
    TEST("fp_abs(10.5)", fp_abs(a), fabs(a));
    TEST("fp_abs(-7.25)", fp_abs(neg_val), fabs(neg_val));
    TEST("fp_abs(0.0)", fp_abs(0.0), 0.0);
    TEST("fp_abs(-123.456)", fp_abs(-123.456), 123.456);
    printf("\n");
    
    /* Summary */
    printf("=== Test Summary ===\n");
    printf("Passed: %d\n", tests_passed);
    printf("Failed: %d\n", tests_failed);
    printf("Total:  %d\n", tests_passed + tests_failed);
    
    if (tests_failed == 0) {
        printf("\nAll tests passed! The ANVIL-generated math library works correctly.\n");
        return 0;
    } else {
        printf("\nSome tests failed. Check the assembly code generation.\n");
        return 1;
    }
}
