/*
 * ANVIL - CPU model catalogue
 *
 * Contains the CPU model feature table, accessors for CPU model names /
 * features / default CPU-per-architecture, and the private
 * anvil_update_cpu_features() helper used by context.c when the model or
 * feature overrides change.
 *
 * Extracted from context.c to keep that file focused on the lifecycle of
 * an anvil_ctx_t itself.
 */

#include "anvil/anvil_internal.h"
#include <stddef.h>

/* ============================================================================
 * CPU Model Information Tables
 * ============================================================================ */

/* CPU model name table */
typedef struct {
    anvil_cpu_model_t model;
    const char *name;
    anvil_arch_t arch;
    anvil_cpu_features_t features;
} cpu_model_info_t;

static const cpu_model_info_t cpu_model_table[] = {
    /* Generic */
    { ANVIL_CPU_GENERIC, "generic", ANVIL_ARCH_COUNT, 0 },
    
    /* PowerPC 32-bit */
    { ANVIL_CPU_PPC_G3, "g3", ANVIL_ARCH_PPC32, 0 },
    { ANVIL_CPU_PPC_G4, "g4", ANVIL_ARCH_PPC32, ANVIL_FEATURE_PPC_ALTIVEC },
    { ANVIL_CPU_PPC_G4E, "g4e", ANVIL_ARCH_PPC32, ANVIL_FEATURE_PPC_ALTIVEC },
    
    /* PowerPC 64-bit */
    { ANVIL_CPU_PPC64_970, "970", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_ALTIVEC | ANVIL_FEATURE_PPC_MFTB },
    { ANVIL_CPU_PPC64_970FX, "970fx", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_ALTIVEC | ANVIL_FEATURE_PPC_MFTB },
    { ANVIL_CPU_PPC64_970MP, "970mp", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_ALTIVEC | ANVIL_FEATURE_PPC_MFTB },
    { ANVIL_CPU_PPC64_POWER4, "power4", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_MFTB },
    { ANVIL_CPU_PPC64_POWER4P, "power4+", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_MFTB },
    { ANVIL_CPU_PPC64_POWER5, "power5", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_MFTB | ANVIL_FEATURE_PPC_POPCNTD },
    { ANVIL_CPU_PPC64_POWER5P, "power5+", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_MFTB | ANVIL_FEATURE_PPC_POPCNTD | ANVIL_FEATURE_PPC_FPRND },
    { ANVIL_CPU_PPC64_POWER6, "power6", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_ALTIVEC | ANVIL_FEATURE_PPC_MFTB | ANVIL_FEATURE_PPC_POPCNTD | 
        ANVIL_FEATURE_PPC_CMPB | ANVIL_FEATURE_PPC_FPRND | ANVIL_FEATURE_PPC_DFP },
    { ANVIL_CPU_PPC64_POWER7, "power7", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_ALTIVEC | ANVIL_FEATURE_PPC_VSX | ANVIL_FEATURE_PPC_MFTB | 
        ANVIL_FEATURE_PPC_POPCNTD | ANVIL_FEATURE_PPC_CMPB | ANVIL_FEATURE_PPC_FPRND | 
        ANVIL_FEATURE_PPC_DFP | ANVIL_FEATURE_PPC_ISEL | ANVIL_FEATURE_PPC_LDBRX |
        ANVIL_FEATURE_PPC_FCPSGN },
    { ANVIL_CPU_PPC64_POWER8, "power8", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_ALTIVEC | ANVIL_FEATURE_PPC_VSX | ANVIL_FEATURE_PPC_MFTB | 
        ANVIL_FEATURE_PPC_POPCNTD | ANVIL_FEATURE_PPC_CMPB | ANVIL_FEATURE_PPC_FPRND | 
        ANVIL_FEATURE_PPC_DFP | ANVIL_FEATURE_PPC_ISEL | ANVIL_FEATURE_PPC_LDBRX |
        ANVIL_FEATURE_PPC_FCPSGN | ANVIL_FEATURE_PPC_HTM | ANVIL_FEATURE_PPC_POWER8_VEC },
    { ANVIL_CPU_PPC64_POWER9, "power9", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_ALTIVEC | ANVIL_FEATURE_PPC_VSX | ANVIL_FEATURE_PPC_MFTB | 
        ANVIL_FEATURE_PPC_POPCNTD | ANVIL_FEATURE_PPC_CMPB | ANVIL_FEATURE_PPC_FPRND | 
        ANVIL_FEATURE_PPC_DFP | ANVIL_FEATURE_PPC_ISEL | ANVIL_FEATURE_PPC_LDBRX |
        ANVIL_FEATURE_PPC_FCPSGN | ANVIL_FEATURE_PPC_POWER8_VEC | ANVIL_FEATURE_PPC_POWER9_VEC },
    { ANVIL_CPU_PPC64_POWER10, "power10", ANVIL_ARCH_PPC64, 
        ANVIL_FEATURE_PPC_ALTIVEC | ANVIL_FEATURE_PPC_VSX | ANVIL_FEATURE_PPC_MFTB | 
        ANVIL_FEATURE_PPC_POPCNTD | ANVIL_FEATURE_PPC_CMPB | ANVIL_FEATURE_PPC_FPRND | 
        ANVIL_FEATURE_PPC_DFP | ANVIL_FEATURE_PPC_ISEL | ANVIL_FEATURE_PPC_LDBRX |
        ANVIL_FEATURE_PPC_FCPSGN | ANVIL_FEATURE_PPC_POWER8_VEC | ANVIL_FEATURE_PPC_POWER9_VEC |
        ANVIL_FEATURE_PPC_MMA | ANVIL_FEATURE_PPC_PCREL },
    
    /* IBM Mainframe */
    { ANVIL_CPU_S370_BASE, "s370", ANVIL_ARCH_S370, 0 },
    { ANVIL_CPU_S370_XA, "s370-xa", ANVIL_ARCH_S370_XA, 0 },
    { ANVIL_CPU_S390_G1, "g1", ANVIL_ARCH_S390, 0 },
    { ANVIL_CPU_S390_G2, "g2", ANVIL_ARCH_S390, 0 },
    { ANVIL_CPU_S390_G3, "g3", ANVIL_ARCH_S390, 0 },
    { ANVIL_CPU_S390_G4, "g4", ANVIL_ARCH_S390, 0 },
    { ANVIL_CPU_S390_G5, "g5", ANVIL_ARCH_S390, ANVIL_FEATURE_ZARCH_HFP_EXT },
    { ANVIL_CPU_S390_G6, "g6", ANVIL_ARCH_S390, ANVIL_FEATURE_ZARCH_HFP_EXT },
    { ANVIL_CPU_ZARCH_Z900, "z900", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM },
    { ANVIL_CPU_ZARCH_Z990, "z990", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM },
    { ANVIL_CPU_ZARCH_Z9, "z9", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM | ANVIL_FEATURE_ZARCH_GIE | ANVIL_FEATURE_ZARCH_DFP },
    { ANVIL_CPU_ZARCH_Z10, "z10", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM | ANVIL_FEATURE_ZARCH_GIE | ANVIL_FEATURE_ZARCH_DFP },
    { ANVIL_CPU_ZARCH_Z196, "z196", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM | ANVIL_FEATURE_ZARCH_GIE | ANVIL_FEATURE_ZARCH_DFP |
        ANVIL_FEATURE_ZARCH_HIGHWORD | ANVIL_FEATURE_ZARCH_INTERLOCKED |
        ANVIL_FEATURE_ZARCH_LOADSTORE | ANVIL_FEATURE_ZARCH_POPCOUNT },
    { ANVIL_CPU_ZARCH_ZEC12, "zec12", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM | ANVIL_FEATURE_ZARCH_GIE | ANVIL_FEATURE_ZARCH_DFP |
        ANVIL_FEATURE_ZARCH_HIGHWORD | ANVIL_FEATURE_ZARCH_INTERLOCKED |
        ANVIL_FEATURE_ZARCH_LOADSTORE | ANVIL_FEATURE_ZARCH_POPCOUNT |
        ANVIL_FEATURE_ZARCH_MISCEXT },
    { ANVIL_CPU_ZARCH_Z13, "z13", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM | ANVIL_FEATURE_ZARCH_GIE | ANVIL_FEATURE_ZARCH_DFP |
        ANVIL_FEATURE_ZARCH_HIGHWORD | ANVIL_FEATURE_ZARCH_INTERLOCKED |
        ANVIL_FEATURE_ZARCH_LOADSTORE | ANVIL_FEATURE_ZARCH_POPCOUNT |
        ANVIL_FEATURE_ZARCH_MISCEXT | ANVIL_FEATURE_ZARCH_VECTOR },
    { ANVIL_CPU_ZARCH_Z14, "z14", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM | ANVIL_FEATURE_ZARCH_GIE | ANVIL_FEATURE_ZARCH_DFP |
        ANVIL_FEATURE_ZARCH_HIGHWORD | ANVIL_FEATURE_ZARCH_INTERLOCKED |
        ANVIL_FEATURE_ZARCH_LOADSTORE | ANVIL_FEATURE_ZARCH_POPCOUNT |
        ANVIL_FEATURE_ZARCH_MISCEXT | ANVIL_FEATURE_ZARCH_MISCEXT2 |
        ANVIL_FEATURE_ZARCH_VECTOR | ANVIL_FEATURE_ZARCH_VECTOR_ENH1 },
    { ANVIL_CPU_ZARCH_Z15, "z15", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM | ANVIL_FEATURE_ZARCH_GIE | ANVIL_FEATURE_ZARCH_DFP |
        ANVIL_FEATURE_ZARCH_HIGHWORD | ANVIL_FEATURE_ZARCH_INTERLOCKED |
        ANVIL_FEATURE_ZARCH_LOADSTORE | ANVIL_FEATURE_ZARCH_POPCOUNT |
        ANVIL_FEATURE_ZARCH_MISCEXT | ANVIL_FEATURE_ZARCH_MISCEXT2 | ANVIL_FEATURE_ZARCH_MISCEXT3 |
        ANVIL_FEATURE_ZARCH_VECTOR | ANVIL_FEATURE_ZARCH_VECTOR_ENH1 | ANVIL_FEATURE_ZARCH_VECTOR_ENH2 },
    { ANVIL_CPU_ZARCH_Z16, "z16", ANVIL_ARCH_ZARCH, 
        ANVIL_FEATURE_ZARCH_EIMM | ANVIL_FEATURE_ZARCH_GIE | ANVIL_FEATURE_ZARCH_DFP |
        ANVIL_FEATURE_ZARCH_HIGHWORD | ANVIL_FEATURE_ZARCH_INTERLOCKED |
        ANVIL_FEATURE_ZARCH_LOADSTORE | ANVIL_FEATURE_ZARCH_POPCOUNT |
        ANVIL_FEATURE_ZARCH_MISCEXT | ANVIL_FEATURE_ZARCH_MISCEXT2 | ANVIL_FEATURE_ZARCH_MISCEXT3 |
        ANVIL_FEATURE_ZARCH_VECTOR | ANVIL_FEATURE_ZARCH_VECTOR_ENH1 | ANVIL_FEATURE_ZARCH_VECTOR_ENH2 |
        ANVIL_FEATURE_ZARCH_NNPA },
    
    /* ARM64 */
    { ANVIL_CPU_ARM64_GENERIC, "generic", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON },
    { ANVIL_CPU_ARM64_CORTEX_A53, "cortex-a53", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 },
    { ANVIL_CPU_ARM64_CORTEX_A55, "cortex-a55", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC },
    { ANVIL_CPU_ARM64_CORTEX_A57, "cortex-a57", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 },
    { ANVIL_CPU_ARM64_CORTEX_A72, "cortex-a72", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 },
    { ANVIL_CPU_ARM64_CORTEX_A73, "cortex-a73", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 },
    { ANVIL_CPU_ARM64_CORTEX_A75, "cortex-a75", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC },
    { ANVIL_CPU_ARM64_CORTEX_A76, "cortex-a76", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA },
    { ANVIL_CPU_ARM64_CORTEX_A77, "cortex-a77", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA },
    { ANVIL_CPU_ARM64_CORTEX_A78, "cortex-a78", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA },
    { ANVIL_CPU_ARM64_CORTEX_X1, "cortex-x1", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA },
    { ANVIL_CPU_ARM64_CORTEX_X2, "cortex-x2", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA | ANVIL_FEATURE_ARM64_SVE2 |
        ANVIL_FEATURE_ARM64_BF16 | ANVIL_FEATURE_ARM64_I8MM },
    { ANVIL_CPU_ARM64_NEOVERSE_N1, "neoverse-n1", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC },
    { ANVIL_CPU_ARM64_NEOVERSE_V1, "neoverse-v1", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_SVE | ANVIL_FEATURE_ARM64_BF16 | ANVIL_FEATURE_ARM64_I8MM },
    { ANVIL_CPU_ARM64_APPLE_M1, "apple-m1", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA },
    { ANVIL_CPU_ARM64_APPLE_M2, "apple-m2", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA | ANVIL_FEATURE_ARM64_BF16 },
    { ANVIL_CPU_ARM64_APPLE_M3, "apple-m3", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA | ANVIL_FEATURE_ARM64_BF16 |
        ANVIL_FEATURE_ARM64_I8MM },
    { ANVIL_CPU_ARM64_APPLE_M4, "apple-m4", ANVIL_ARCH_ARM64, 
        ANVIL_FEATURE_ARM64_NEON | ANVIL_FEATURE_ARM64_CRC32 | ANVIL_FEATURE_ARM64_AES |
        ANVIL_FEATURE_ARM64_SHA1 | ANVIL_FEATURE_ARM64_SHA256 | ANVIL_FEATURE_ARM64_ATOMICS |
        ANVIL_FEATURE_ARM64_DOTPROD | ANVIL_FEATURE_ARM64_FP16 | ANVIL_FEATURE_ARM64_RCPC |
        ANVIL_FEATURE_ARM64_JSCVT | ANVIL_FEATURE_ARM64_FCMA | ANVIL_FEATURE_ARM64_BF16 |
        ANVIL_FEATURE_ARM64_I8MM | ANVIL_FEATURE_ARM64_SME },
    
    /* x86 32-bit */
    { ANVIL_CPU_X86_I386, "i386", ANVIL_ARCH_X86, 0 },
    { ANVIL_CPU_X86_I486, "i486", ANVIL_ARCH_X86, 0 },
    { ANVIL_CPU_X86_PENTIUM, "pentium", ANVIL_ARCH_X86, 0 },
    { ANVIL_CPU_X86_PENTIUM_MMX, "pentium-mmx", ANVIL_ARCH_X86, ANVIL_FEATURE_X86_MMX },
    { ANVIL_CPU_X86_PENTIUM_PRO, "pentium-pro", ANVIL_ARCH_X86, 0 },
    { ANVIL_CPU_X86_PENTIUM2, "pentium2", ANVIL_ARCH_X86, ANVIL_FEATURE_X86_MMX },
    { ANVIL_CPU_X86_PENTIUM3, "pentium3", ANVIL_ARCH_X86, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE },
    { ANVIL_CPU_X86_PENTIUM4, "pentium4", ANVIL_ARCH_X86, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 },
    { ANVIL_CPU_X86_K6, "k6", ANVIL_ARCH_X86, ANVIL_FEATURE_X86_MMX },
    { ANVIL_CPU_X86_ATHLON, "athlon", ANVIL_ARCH_X86, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE },
    
    /* x86-64 */
    { ANVIL_CPU_X86_64_GENERIC, "x86-64", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 },
    { ANVIL_CPU_X86_64_NOCONA, "nocona", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 },
    { ANVIL_CPU_X86_64_CORE2, "core2", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 },
    { ANVIL_CPU_X86_64_NEHALEM, "nehalem", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT },
    { ANVIL_CPU_X86_64_WESTMERE, "westmere", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT },
    { ANVIL_CPU_X86_64_SANDYBRIDGE, "sandybridge", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX },
    { ANVIL_CPU_X86_64_IVYBRIDGE, "ivybridge", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX },
    { ANVIL_CPU_X86_64_HASWELL, "haswell", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE },
    { ANVIL_CPU_X86_64_BROADWELL, "broadwell", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE },
    { ANVIL_CPU_X86_64_SKYLAKE, "skylake", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE },
    { ANVIL_CPU_X86_64_ICELAKE, "icelake", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE |
        ANVIL_FEATURE_X86_AVX512F },
    { ANVIL_CPU_X86_64_ALDERLAKE, "alderlake", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE },
    { ANVIL_CPU_X86_64_K8, "k8", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 },
    { ANVIL_CPU_X86_64_K10, "k10", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSE41 | ANVIL_FEATURE_X86_SSE42 |
        ANVIL_FEATURE_X86_POPCNT },
    { ANVIL_CPU_X86_64_BULLDOZER, "bulldozer", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_FMA },
    { ANVIL_CPU_X86_64_ZEN, "zen", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE },
    { ANVIL_CPU_X86_64_ZEN2, "zen2", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE },
    { ANVIL_CPU_X86_64_ZEN3, "zen3", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE },
    { ANVIL_CPU_X86_64_ZEN4, "zen4", ANVIL_ARCH_X86_64, 
        ANVIL_FEATURE_X86_MMX | ANVIL_FEATURE_X86_SSE | ANVIL_FEATURE_X86_SSE2 |
        ANVIL_FEATURE_X86_SSE3 | ANVIL_FEATURE_X86_SSSE3 | ANVIL_FEATURE_X86_SSE41 |
        ANVIL_FEATURE_X86_SSE42 | ANVIL_FEATURE_X86_POPCNT | ANVIL_FEATURE_X86_AVX |
        ANVIL_FEATURE_X86_AVX2 | ANVIL_FEATURE_X86_FMA | ANVIL_FEATURE_X86_BMI1 |
        ANVIL_FEATURE_X86_BMI2 | ANVIL_FEATURE_X86_LZCNT | ANVIL_FEATURE_X86_MOVBE |
        ANVIL_FEATURE_X86_AVX512F },
    
    /* Sentinel */
    { 0, NULL, 0, 0 }
};

/* Find CPU model info */
static const cpu_model_info_t *find_cpu_model_info(anvil_cpu_model_t model)
{
    for (size_t i = 0; cpu_model_table[i].name != NULL; i++) {
        if (cpu_model_table[i].model == model) {
            return &cpu_model_table[i];
        }
    }
    return NULL;
}

/* Update effective CPU features based on model and overrides */
void anvil_update_cpu_features(anvil_ctx_t *ctx)
{
    anvil_cpu_features_t base_features = 0;
    
    const cpu_model_info_t *info = find_cpu_model_info(ctx->cpu_model);
    if (info) {
        base_features = info->features;
    }
    
    /* Apply overrides: enable first, then disable */
    ctx->cpu_features = (base_features | ctx->features_enabled) & ~ctx->features_disabled;
}

/* ============================================================================
 * Public CPU-model accessors (also used by the ctx_* setters in context.c).
 * ============================================================================ */

const char *anvil_cpu_model_name(anvil_cpu_model_t cpu)
{
    const cpu_model_info_t *info = find_cpu_model_info(cpu);
    return info ? info->name : "unknown";
}

anvil_cpu_model_t anvil_arch_default_cpu(anvil_arch_t arch)
{
    switch (arch) {
        case ANVIL_ARCH_X86:     return ANVIL_CPU_X86_I386;
        case ANVIL_ARCH_X86_64:  return ANVIL_CPU_X86_64_GENERIC;
        case ANVIL_ARCH_S370:    return ANVIL_CPU_S370_BASE;
        case ANVIL_ARCH_S370_XA: return ANVIL_CPU_S370_XA;
        case ANVIL_ARCH_S390:    return ANVIL_CPU_S390_G5;
        case ANVIL_ARCH_ZARCH:   return ANVIL_CPU_ZARCH_Z900;
        case ANVIL_ARCH_PPC32:   return ANVIL_CPU_PPC_G3;
        case ANVIL_ARCH_PPC64:   return ANVIL_CPU_PPC64_POWER4;
        case ANVIL_ARCH_PPC64LE: return ANVIL_CPU_PPC64_POWER8;
        case ANVIL_ARCH_ARM64:   return ANVIL_CPU_ARM64_GENERIC;
        default:                 return ANVIL_CPU_GENERIC;
    }
}

anvil_cpu_features_t anvil_cpu_model_features(anvil_cpu_model_t cpu)
{
    const cpu_model_info_t *info = find_cpu_model_info(cpu);
    return info ? info->features : 0;
}

/* Opaque accessors so context.c can validate a candidate CPU without
 * re-exposing cpu_model_info_t across the codebase. */
const void *anvil_cpu_table_find(anvil_cpu_model_t model)
{
    return (const void *)find_cpu_model_info(model);
}

const char *anvil_cpu_table_info_name(const void *opaque)
{
    return opaque ? ((const cpu_model_info_t *)opaque)->name : NULL;
}

anvil_arch_t anvil_cpu_table_info_arch(const void *opaque)
{
    return opaque ? ((const cpu_model_info_t *)opaque)->arch : ANVIL_ARCH_COUNT;
}
