// Generated by ANVIL for ARM64 (AArch64) - macOS
	.build_version macos, 11, 0
	.section __TEXT,__text,regular,pure_instructions

	.globl _main
	.p2align 2
_main:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #160
	str xzr, [x29, #-160]
	mov x9, #5
	str x9, [x29, #-8]
	str xzr, [x29, #-168]
	mov x9, #3
	str x9, [x29, #-16]
	ldr x0, [x29, #-8]
	str x0, [x29, #-24]
	ldr x0, [x29, #-16]
	str x0, [x29, #-32]
	ldr x9, [x29, #-24]
	ldr x10, [x29, #-32]
	add x0, x9, x10
	str x0, [x29, #-40]
	ldr x9, [x29, #-40]
	mov x0, x9
	bl _print_digit
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-48]
	ldr x0, [x29, #-8]
	str x0, [x29, #-56]
	ldr x0, [x29, #-16]
	str x0, [x29, #-64]
	ldr x9, [x29, #-56]
	ldr x10, [x29, #-64]
	sub x0, x9, x10
	str x0, [x29, #-72]
	ldr x9, [x29, #-72]
	mov x0, x9
	bl _print_digit
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-80]
	str xzr, [x29, #-176]
	ldr x0, [x29, #-8]
	str x0, [x29, #-96]
	ldr x0, [x29, #-16]
	str x0, [x29, #-104]
	ldr x9, [x29, #-96]
	ldr x10, [x29, #-104]
	mul x0, x9, x10
	str x0, [x29, #-112]
	ldr x9, [x29, #-112]
	str x9, [x29, #-88]
	ldr x0, [x29, #-88]
	str x0, [x29, #-120]
	ldr x9, [x29, #-120]
	mov x10, #10
	sdiv x0, x9, x10
	str x0, [x29, #-128]
	ldr x9, [x29, #-128]
	mov x0, x9
	bl _print_digit
	ldr x0, [x29, #-88]
	str x0, [x29, #-136]
	ldr x9, [x29, #-136]
	mov x10, #10
	sdiv x11, x9, x10
	msub x0, x11, x10, x9
	str x0, [x29, #-144]
	ldr x9, [x29, #-144]
	mov x0, x9
	bl _print_digit
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-152]
	mov x0, #0
	add sp, sp, #160
	ldp x29, x30, [sp], #16
	ret
	mov x0, #0
	add sp, sp, #160
	ldp x29, x30, [sp], #16
	ret

	.globl _print_digit
	.p2align 2
_print_digit:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #48
	str x0, [x29, #-40]
	str xzr, [x29, #-48]
	ldr x9, [x29, #-40]
	str x9, [x29, #-8]
	ldr x0, [x29, #-8]
	str x0, [x29, #-16]
	mov x9, #48
	ldr x10, [x29, #-16]
	add x0, x9, x10
	str x0, [x29, #-24]
	ldr x9, [x29, #-24]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-32]
	add sp, sp, #48
	ldp x29, x30, [sp], #16
	ret

