// Generated by ANVIL for ARM64 (AArch64) - macOS
	.build_version macos, 11, 0
	.section __TEXT,__text,regular,pure_instructions

	.globl _main
	.p2align 2
_main:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #192
	str xzr, [x29, #-200]
	str xzr, [x29, #-208]
	mov x9, #0
	str x9, [x29, #-16]
	b .Lmain_for.cond
.Lmain_for.cond:
	ldr x0, [x29, #-16]
	str x0, [x29, #-24]
	ldr x9, [x29, #-24]
	mov x10, #5
	cmp x9, x10
	cset x0, lt
	str x0, [x29, #-32]
	ldr x9, [x29, #-32]
	mov x10, #0
	cmp x9, x10
	cset x0, ne
	str x0, [x29, #-40]
	ldr x9, [x29, #-40]
	cbnz x9, .Lmain_for.body
	b .Lmain_for.end
.Lmain_for.body:
	ldr x0, [x29, #-8]
	str x0, [x29, #-48]
	ldr x0, [x29, #-16]
	str x0, [x29, #-56]
	ldr x9, [x29, #-48]
	ldr x10, [x29, #-56]
	add x0, x9, x10, lsl #2
	str x0, [x29, #-64]
	ldr x0, [x29, #-16]
	str x0, [x29, #-72]
	ldr x9, [x29, #-72]
	mov x10, #2
	mul x0, x9, x10
	str x0, [x29, #-80]
	ldr x9, [x29, #-80]
	ldr x10, [x29, #-64]
	str w9, [x10]
	b .Lmain_for.incr
.Lmain_for.incr:
	ldr x0, [x29, #-16]
	str x0, [x29, #-88]
	ldr x9, [x29, #-88]
	mov x10, #1
	add x0, x9, x10
	str x0, [x29, #-96]
	ldr x9, [x29, #-96]
	str x9, [x29, #-16]
	b .Lmain_for.cond
.Lmain_for.end:
	mov x9, #0
	str x9, [x29, #-16]
	b .Lmain_for.cond
.Lmain_for.cond:
	ldr x0, [x29, #-16]
	str x0, [x29, #-104]
	ldr x9, [x29, #-104]
	mov x10, #5
	cmp x9, x10
	cset x0, lt
	str x0, [x29, #-112]
	ldr x9, [x29, #-112]
	mov x10, #0
	cmp x9, x10
	cset x0, ne
	str x0, [x29, #-120]
	ldr x9, [x29, #-120]
	cbnz x9, .Lmain_for.body
	b .Lmain_for.end
.Lmain_for.body:
	ldr x0, [x29, #-8]
	str x0, [x29, #-128]
	ldr x0, [x29, #-16]
	str x0, [x29, #-136]
	ldr x9, [x29, #-128]
	ldr x10, [x29, #-136]
	add x0, x9, x10, lsl #2
	str x0, [x29, #-144]
	ldr x9, [x29, #-144]
	ldr w0, [x9]
	str x0, [x29, #-152]
	mov x9, #48
	ldr x10, [x29, #-152]
	add x0, x9, x10
	str x0, [x29, #-160]
	ldr x9, [x29, #-160]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-168]
	b .Lmain_for.incr
.Lmain_for.incr:
	ldr x0, [x29, #-16]
	str x0, [x29, #-176]
	ldr x9, [x29, #-176]
	mov x10, #1
	add x0, x9, x10
	str x0, [x29, #-184]
	ldr x9, [x29, #-184]
	str x9, [x29, #-16]
	b .Lmain_for.cond
.Lmain_for.end:
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-192]
	mov x0, #0
	add sp, sp, #192
	ldp x29, x30, [sp], #16
	ret
	mov x0, #0
	add sp, sp, #192
	ldp x29, x30, [sp], #16
	ret

