// Generated by ANVIL for ARM64 (AArch64) - macOS
	.build_version macos, 11, 0
	.section __TEXT,__text,regular,pure_instructions

	.globl _main
	.p2align 2
_main:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #144
	str xzr, [x29, #-144]
	mov x9, #10
	str x9, [x29, #-8]
	ldr x0, [x29, #-8]
	str x0, [x29, #-16]
	ldr x9, [x29, #-16]
	mov x10, #5
	cmp x9, x10
	cset x0, gt
	str x0, [x29, #-24]
	ldr x9, [x29, #-24]
	mov x10, #0
	cmp x9, x10
	cset x0, ne
	str x0, [x29, #-32]
	ldr x9, [x29, #-32]
	cbnz x9, .Lmain_if.then
	b .Lmain_if.else
.Lmain_if.then:
	mov x9, #89
	mov x0, x9
	bl _putchar
	str x0, [x29, #-40]
	b .Lmain_if.end
.Lmain_if.else:
	mov x9, #78
	mov x0, x9
	bl _putchar
	str x0, [x29, #-48]
	b .Lmain_if.end
.Lmain_if.end:
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-56]
	ldr x0, [x29, #-8]
	str x0, [x29, #-64]
	ldr x9, [x29, #-64]
	mov x10, #5
	cmp x9, x10
	cset x0, lt
	str x0, [x29, #-72]
	ldr x9, [x29, #-72]
	mov x10, #0
	cmp x9, x10
	cset x0, ne
	str x0, [x29, #-80]
	ldr x9, [x29, #-80]
	cbnz x9, .Lmain_if.then
	b .Lmain_if.else
.Lmain_if.then:
	mov x9, #65
	mov x0, x9
	bl _putchar
	str x0, [x29, #-88]
	b .Lmain_if.end
.Lmain_if.else:
	ldr x0, [x29, #-8]
	str x0, [x29, #-96]
	ldr x9, [x29, #-96]
	mov x10, #10
	cmp x9, x10
	cset x0, eq
	str x0, [x29, #-104]
	ldr x9, [x29, #-104]
	mov x10, #0
	cmp x9, x10
	cset x0, ne
	str x0, [x29, #-112]
	ldr x9, [x29, #-112]
	cbnz x9, .Lmain_if.then
	b .Lmain_if.else
.Lmain_if.end:
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-120]
	mov x0, #0
	add sp, sp, #144
	ldp x29, x30, [sp], #16
	ret
	mov x0, #0
	add sp, sp, #144
	ldp x29, x30, [sp], #16
	ret
.Lmain_if.then:
	mov x9, #66
	mov x0, x9
	bl _putchar
	str x0, [x29, #-128]
	b .Lmain_if.end
.Lmain_if.else:
	mov x9, #67
	mov x0, x9
	bl _putchar
	str x0, [x29, #-136]
	b .Lmain_if.end
.Lmain_if.end:
	b .Lmain_if.end

