// Generated by ANVIL for ARM64 (AArch64) - macOS
	.build_version macos, 11, 0
	.section __TEXT,__text,regular,pure_instructions

	.globl _main
	.p2align 2
_main:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #32
	mov x0, x9
	bl _putchar
	str x0, [x29, #-8]
	bl _increment
	mov x0, x9
	bl _putchar
	str x0, [x29, #-16]
	bl _increment
	bl _increment
	mov x0, x9
	bl _putchar
	str x0, [x29, #-24]
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-32]
	mov x0, #0
	add sp, sp, #32
	ldp x29, x30, [sp], #16
	ret
	mov x0, #0
	add sp, sp, #32
	ldp x29, x30, [sp], #16
	ret

	.globl _increment
	.p2align 2
_increment:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	ldp x29, x30, [sp], #16
	ret

	.data
	.globl _counter
	.p2align 2
_counter:
	.zero 4

