// Generated by ANVIL for ARM64 (AArch64) - macOS
	.build_version macos, 11, 0
	.section __TEXT,__text,regular,pure_instructions

	.globl _main
	.p2align 2
_main:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #160
	str xzr, [x29, #-160]
	mov x9, #0
	str x9, [x29, #-8]
	b .Lmain_while.cond
.Lmain_while.cond:
	ldr x0, [x29, #-8]
	str x0, [x29, #-16]
	ldr x9, [x29, #-16]
	mov x10, #5
	cmp x9, x10
	cset x0, lt
	str x0, [x29, #-24]
	ldr x9, [x29, #-24]
	mov x10, #0
	cmp x9, x10
	cset x0, ne
	str x0, [x29, #-32]
	ldr x9, [x29, #-32]
	cbnz x9, .Lmain_while.body
	b .Lmain_while.end
.Lmain_while.body:
	ldr x0, [x29, #-8]
	str x0, [x29, #-40]
	mov x9, #48
	ldr x10, [x29, #-40]
	add x0, x9, x10
	str x0, [x29, #-48]
	ldr x9, [x29, #-48]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-56]
	ldr x0, [x29, #-8]
	str x0, [x29, #-64]
	ldr x9, [x29, #-64]
	mov x10, #1
	add x0, x9, x10
	str x0, [x29, #-72]
	ldr x9, [x29, #-72]
	str x9, [x29, #-8]
	b .Lmain_while.cond
.Lmain_while.end:
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-80]
	mov x9, #5
	str x9, [x29, #-8]
	b .Lmain_for.cond
.Lmain_for.cond:
	ldr x0, [x29, #-8]
	str x0, [x29, #-88]
	ldr x9, [x29, #-88]
	mov x10, #10
	cmp x9, x10
	cset x0, lt
	str x0, [x29, #-96]
	ldr x9, [x29, #-96]
	mov x10, #0
	cmp x9, x10
	cset x0, ne
	str x0, [x29, #-104]
	ldr x9, [x29, #-104]
	cbnz x9, .Lmain_for.body
	b .Lmain_for.end
.Lmain_for.body:
	ldr x0, [x29, #-8]
	str x0, [x29, #-112]
	mov x9, #48
	ldr x10, [x29, #-112]
	add x0, x9, x10
	str x0, [x29, #-120]
	ldr x9, [x29, #-120]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-128]
	b .Lmain_for.incr
.Lmain_for.incr:
	ldr x0, [x29, #-8]
	str x0, [x29, #-136]
	ldr x9, [x29, #-136]
	mov x10, #1
	add x0, x9, x10
	str x0, [x29, #-144]
	ldr x9, [x29, #-144]
	str x9, [x29, #-8]
	b .Lmain_for.cond
.Lmain_for.end:
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-152]
	mov x0, #0
	add sp, sp, #160
	ldp x29, x30, [sp], #16
	ret
	mov x0, #0
	add sp, sp, #160
	ldp x29, x30, [sp], #16
	ret

