// Generated by ANVIL for ARM64 (AArch64) - macOS
	.build_version macos, 11, 0
	.section __TEXT,__text,regular,pure_instructions

	.globl _main
	.p2align 2
_main:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #128
	str xzr, [x29, #-136]
	mov x9, #3
	str x9, [x29, #-8]
	str xzr, [x29, #-144]
	mov x9, #7
	str x9, [x29, #-16]
	ldr x0, [x29, #-8]
	str x0, [x29, #-24]
	mov x9, #48
	ldr x10, [x29, #-24]
	add x0, x9, x10
	str x0, [x29, #-32]
	ldr x9, [x29, #-32]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-40]
	ldr x0, [x29, #-16]
	str x0, [x29, #-48]
	mov x9, #48
	ldr x10, [x29, #-48]
	add x0, x9, x10
	str x0, [x29, #-56]
	ldr x9, [x29, #-56]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-64]
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-72]
	sub x9, x29, #8
	sub x10, x29, #16
	mov x0, x9
	mov x1, x10
	bl _swap
	ldr x0, [x29, #-8]
	str x0, [x29, #-80]
	mov x9, #48
	ldr x10, [x29, #-80]
	add x0, x9, x10
	str x0, [x29, #-88]
	ldr x9, [x29, #-88]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-96]
	ldr x0, [x29, #-16]
	str x0, [x29, #-104]
	mov x9, #48
	ldr x10, [x29, #-104]
	add x0, x9, x10
	str x0, [x29, #-112]
	ldr x9, [x29, #-112]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-120]
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-128]
	mov x0, #0
	add sp, sp, #128
	ldp x29, x30, [sp], #16
	ret
	mov x0, #0
	add sp, sp, #128
	ldp x29, x30, [sp], #16
	ret

	.globl _swap
	.p2align 2
_swap:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #96
	str x0, [x29, #-88]
	str x1, [x29, #-96]
	str xzr, [x29, #-104]
	ldr x9, [x29, #-88]
	str x9, [x29, #-8]
	str xzr, [x29, #-112]
	ldr x9, [x29, #-96]
	str x9, [x29, #-16]
	str xzr, [x29, #-120]
	ldr x0, [x29, #-8]
	str x0, [x29, #-32]
	ldr x9, [x29, #-32]
	ldr w0, [x9]
	str x0, [x29, #-40]
	ldr x9, [x29, #-40]
	str x9, [x29, #-24]
	ldr x0, [x29, #-8]
	str x0, [x29, #-48]
	ldr x0, [x29, #-16]
	str x0, [x29, #-56]
	ldr x9, [x29, #-56]
	ldr w0, [x9]
	str x0, [x29, #-64]
	ldr x9, [x29, #-64]
	ldr x10, [x29, #-48]
	str w9, [x10]
	ldr x0, [x29, #-16]
	str x0, [x29, #-72]
	ldr x0, [x29, #-24]
	str x0, [x29, #-80]
	ldr x9, [x29, #-80]
	ldr x10, [x29, #-72]
	str w9, [x10]
	add sp, sp, #96
	ldp x29, x30, [sp], #16
	ret

