// Generated by ANVIL for ARM64 (AArch64) - macOS
	.build_version macos, 11, 0
	.section __TEXT,__text,regular,pure_instructions

	.globl _main
	.p2align 2
_main:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	sub sp, sp, #176
	str xzr, [x29, #-184]
	sub x9, x29, #8
	mov x0, x9
	str x0, [x29, #-16]
	mov x9, #3
	ldr x10, [x29, #-16]
	str w9, [x10]
	sub x9, x29, #8
	add x0, x9, #4
	str x0, [x29, #-24]
	mov x9, #5
	ldr x10, [x29, #-24]
	str w9, [x10]
	sub x9, x29, #8
	mov x0, x9
	str x0, [x29, #-32]
	ldr x9, [x29, #-32]
	ldr w0, [x9]
	str x0, [x29, #-40]
	mov x9, #48
	ldr x10, [x29, #-40]
	add x0, x9, x10
	str x0, [x29, #-48]
	ldr x9, [x29, #-48]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-56]
	sub x9, x29, #8
	add x0, x9, #4
	str x0, [x29, #-64]
	ldr x9, [x29, #-64]
	ldr w0, [x9]
	str x0, [x29, #-72]
	mov x9, #48
	ldr x10, [x29, #-72]
	add x0, x9, x10
	str x0, [x29, #-80]
	ldr x9, [x29, #-80]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-88]
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-96]
	str xzr, [x29, #-192]
	sub x9, x29, #8
	mov x0, x9
	str x0, [x29, #-112]
	ldr x9, [x29, #-112]
	ldr w0, [x9]
	str x0, [x29, #-120]
	sub x9, x29, #8
	add x0, x9, #4
	str x0, [x29, #-128]
	ldr x9, [x29, #-128]
	ldr w0, [x9]
	str x0, [x29, #-136]
	ldr x9, [x29, #-120]
	ldr x10, [x29, #-136]
	add x0, x9, x10
	str x0, [x29, #-144]
	ldr x9, [x29, #-144]
	str x9, [x29, #-104]
	ldr x0, [x29, #-104]
	str x0, [x29, #-152]
	mov x9, #48
	ldr x10, [x29, #-152]
	add x0, x9, x10
	str x0, [x29, #-160]
	ldr x9, [x29, #-160]
	mov x0, x9
	bl _putchar
	str x0, [x29, #-168]
	mov x9, #10
	mov x0, x9
	bl _putchar
	str x0, [x29, #-176]
	mov x0, #0
	add sp, sp, #176
	ldp x29, x30, [sp], #16
	ret
	mov x0, #0
	add sp, sp, #176
	ldp x29, x30, [sp], #16
	ret

